accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = "accounts"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.home, name="home"),
    path('create/invoice', v.create_invoice, name="create_invoice"),
    path('edit/invoice/<int:pk>', v.edit_invoice, name="edit_invoice"),
    path('delete/invoice/<int:pk>/', v.delete_invoice, name='delete_invoice'),
    path('summary', v.summary, name="summary"),
    path('cost/edit/<int:pk>', v.edit_cost, name="edit_cost"),
    path('invoice/generate/<int:pk>', v.invoice_data, name="invoice_data"),
    path('invoice', v.get_invoice_data, name="get_invoice_data"),
    path('salaries', v.salary_view, name="salary_view"),
    path('salary/edit/<int:pk>', v.edit_salary, name="edit_salary"),
    path('login', v.user_login, name="login"),
    path('register', v.user_registration, name="register"),
    path('logout', v.logout_view, name="logout")
]

quote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

templates/salary/edit.html
{% extends 'others/base.html' %} 
{% block title %}Edit Salary{% endblock %}
{% block content %}
{% include "others/navbar.html" %}

<form class="max-w-3xl mx-auto py-24" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="mb-10 text-3xl font-bold text-red-500 gap-x-16">Edit Invoice</h1>
    <div class="grid grid-cols-2 gap-x-8">
        {% for field in form %}
        <div class="mb-4">
            <label for="{{ field.id_for_label }}" class="block text-sm uppercase font-medium mb-2">{{ field.label }}</label>
            {{ field }}
        </div>
        {% endfor %}
    </div>
  

    <input type="submit" class="text-white bg-gray-400 hover:bg-gray-500
     focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 
     mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" value="Submit">
</form>



{% include 'others/footer.html' %}



{% endblock %}

templates/salary/index.html
{% extends 'others/base.html' %} 
{% load humanize %}
{% block title %} Edit Salaries {% endblock %}
{% block content %} 
{% include "others/navbar.html" %}
{% if messages %}
  <div class="p-4 text-center mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
    {% for message in messages %}
      <span class="font-medium">{{ message }}</span>
    {% endfor %}
  </div>
{% endif %}

<div class="flex justify-center px-24 pb-32 pt-16">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 summary_table">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-gray-400 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              ID
            </th>

            <th scope="col" class="px-6 py-3">
               Task
              </th>
    
            <th scope="col" class="px-6 py-3">
              Salary
            </th>

            <th scope="col" class="px-6 py-3">
                
            </th>

        
          </tr>
        </thead>
        <tbody>
            {% for salary in salaries %}
            <tr class="bg-white border-b">
                <th scope="row" class="px-6 py-4 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  {{ salary.id }}
                </th>

                <th scope="row" class="px-6 py-4 text-sm text-gray-900 whitespace-nowrap dark:text-white">
                    {{ salary.task }}
                  </th>

                  <th scope="row" class="px-6 py-4 text-sm font-normal text-gray-900 whitespace-nowrap dark:text-white">
                    {{ salary.salary }}
                  </th>


                  <th scope="row" class="px-6 py-4 text-sm text-gray-900 font-normal whitespace-nowrap dark:text-white">
                    <a href="{% url 'accounts:edit_salary' salary.id %}" class="hover:text-blue-500 text-orange-500">Edit</a>
                  </th>



        
              </tr>
            {% endfor %}
         
        <tfoot class="bg-white dark:bg-gray-800 border-b bg-gray-200">
        </tfoot>
      </table>
</div>
{% include "others/footer.html" %}
{% endblock %} 