accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = "accounts"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.home, name="home"),
    path('create/invoice', v.create_invoice, name="create_invoice"),
    path('edit/invoice/<int:pk>', v.edit_invoice, name="edit_invoice"),
    path('delete/invoice/<int:pk>/', v.delete_invoice, name='delete_invoice'),
    path('summary', v.summary, name="summary"),
    path('cost/edit/<int:pk>', v.edit_cost, name="edit_cost"),
    path('invoice/generate/<int:pk>', v.invoice_data, name="invoice_data"),
    path('invoice', v.get_invoice_data, name="get_invoice_data"),
    path('salaries', v.salary_view, name="salary_view"),
    path('salary/edit/<int:pk>', v.edit_salary, name="edit_salary"),
    path('login', v.user_login, name="login"),
    path('register', v.user_registration, name="register"),
    path('logout', v.logout_view, name="logout")
]

quote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

templates/index.html
{% extends 'others/base.html' %} 
{% load humanize %}
{% block title %} Welcome, {{ request.user }} {% endblock %}
{% block content %} 
{% include "others/navbar.html" %}

{% if messages %}
  <div class="p-4 text-center mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
    {% for message in messages %}
      <span class="font-medium">{{ message }}</span>
    {% endfor %}
  </div>
{% endif %}

<div class="flex items-center max-w-2xl gap-x-48 mx-auto pt-24">
  
<form class="flex">   
    <label for="simple-search" class="sr-only">Search</label>
    <div class="relative w-full">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" 
            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5v10M3 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0 10a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm12 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm0 0V6a3 3 0 0 0-3-3H9m1.5-2-2 2 2 2"/>
            </svg>
        </div>
        <input type="text" id="simple-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" 
        placeholder="Search By Invoice Title" required />
    </div>
    <button type="submit" class="p-2.5 ms-2 text-sm font-medium text-white bg-gray-400 rounded-lg border hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        <span>Search</span>
    </button>
</form>
<div>
  <a href="{% url 'accounts:create_invoice' %}"><button type="button" class="text-white bg-gray-400 hover:bg-gray-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 
  dark:bg-blue-600 dark:hover:bg-gray-500 focus:outline-none dark:focus:ring-gray-800">Create New Invoice</button></a>
</div>


</div>
<div class="flex justify-center px-24 py-10">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 summary_table">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-gray-400 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Invoice Title
            </th>

            <th scope="col" class="px-6 py-3">
               Company Name
              </th>
    
            <th scope="col" class="px-6 py-3">
              Invoice ID
            </th>

            <th scope="col" class="px-6 py-3">
                Total Cost
            </th>

            <th scope="col" class="px-6 py-3">
          </th>

            <th scope="col" class="px-6 py-3">
                
            </th>

            
            <th scope="col" class="px-6 py-3">
                
            </th>
          </tr>
        </thead>
        <tbody>
            {% for price in prices %}
            <tr class="bg-white border-b">
                <th scope="row" class="px-6 py-4 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  {{ price.invoice_title }}
                </th>

                <th scope="row" class="px-6 py-4 text-sm text-gray-900 whitespace-nowrap dark:text-white">
                    {{ price.company_name }}
                  </th>

                  <th scope="row" class="px-6 py-4 text-sm font-normal text-gray-900 whitespace-nowrap dark:text-white">
                    {{ price.invoice_id }}
                  </th>

                  <th scope="row" class="px-6 py-4 text-sm font-normal text-gray-900 whitespace-nowrap dark:text-white">
                    ₦{{ price.final_cost|floatformat:"2"|intcomma }}
                  </th>

                  <th scope="row" class="px-6 py-4 text-sm text-gray-900 font-normal whitespace-nowrap dark:text-white">
                    <a href="{% url 'accounts:invoice_data' price.id %}" class="hover:text-blue-500 text-orange-500">Generate</a>
                  </th>

                  <th scope="row" class="px-6 py-4 text-sm text-gray-900 font-normal whitespace-nowrap dark:text-white">
                    <a href="{% url 'accounts:edit_invoice' price.id %}" class="hover:text-blue-500 text-orange-500">Edit</a>
                  </th>

                  <th scope="row" class="px-6 py-4 text-sm font-normal text-gray-900 whitespace-nowrap dark:text-white">
                    <a href="{% url 'accounts:delete_invoice' price.id %}" class="hover:text-blue-500 text-orange-500">Delete</a>
                  </th>

        
              </tr>
            {% endfor %}
         
        <tfoot class="bg-white dark:bg-gray-800 border-b bg-gray-200">
        </tfoot>
      </table>
</div>
{% include "others/footer.html" %}
{% endblock %} 