accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

app_name = "accounts"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.home, name="home"),
    path('create/invoice', v.create_invoice, name="create_invoice"),
    path('edit/invoice/<int:pk>', v.edit_invoice, name="edit_invoice"),
    path('delete/invoice/<int:pk>/', v.delete_invoice, name='delete_invoice'),
    path('summary', v.summary, name="summary"),
    path('cost/edit/<int:pk>', v.edit_cost, name="edit_cost"),
    path('invoice/generate/<int:pk>', v.invoice_data, name="invoice_data"),
    path('invoice', v.get_invoice_data, name="get_invoice_data"),
    path('salaries', v.salary_view, name="salary_view"),
    path('salary/edit/<int:pk>', v.edit_salary, name="edit_salary"),
    path('login', v.user_login, name="login"),
    path('register', v.user_registration, name="register"),
    path('logout', v.logout_view, name="logout")
]

quote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

templates/others/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
  <link rel="shortcut icon" type="image/png" href="{% static 'img/logo.png' %}">
  <script src="https://cdn.tailwindcss.com"></script>
  <style type="text/tailwindcss">
    @layer utilities {
      .content-auto {
        content-visibility: auto;
      }
    }
  </style>


  <title>{% block title %}{% endblock %}</title>
</head>

<body>

    {% block content %}
    
    {% endblock %}

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
{% block script_block %}
{% endblock  %}

</html>

templates/others/edit_cost.html
{% extends 'others/base.html' %} 
{% block title %}Edit Overhead Cost{% endblock %}
{% block content %}
{% include "others/navbar.html" %}

<form class="max-w-3xl mx-auto py-24" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="mb-10 text-3xl font-bold text-red-500 gap-x-16">Edit Invoice</h1>
    <div class="grid grid-cols-2 gap-x-8">
        {% for field in form %}
        <div class="mb-4">
            <label for="{{ field.id_for_label }}" class="block text-sm uppercase font-medium mb-2">{{ field.label }}</label>
            {{ field }}
        </div>
        {% endfor %}
    </div>
  

    <input type="submit" class="text-white bg-gray-400 hover:bg-gray-500
     focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 
     mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" value="Submit">
</form>



{% include 'others/footer.html' %}



{% endblock %}

templates/others/footer.html

<footer class="bg-green-500 fixed bottom-0 w-[100vw]">
        <span class="block sm:text-center font-medium py-6">© 2024 
            <a href="https://orangevfx.com/" class="hover:underline">Orange VFX Studios</a>. All Rights Reserved.</span>
</footer>


templates/others/init.html
<div class="initialize flex-col flex bg-green-200 p-24">
  <div class="my-4">
    <h1 class="text-2xl font-bold text-red-600">Hello, {{ request.user|capfirst }}</h1>
  </div>

  <div class="initialize_sub flex flex-col gap-y-4">
    <div class="grid auto-cols-max gap-x-24">
      <div class="flex flex-col gap-y-2">


        <div class="mb-4">
          <label
            class="block text-gray-700 text-sm font-bold mb-2"
            for="production_days"
          >
            Total Number of Days For Production
          </label>
          <input
            name="production_days"
            min="0"
            value="0"
            id="production_days"
            class="form-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            type="number"
          />
        </div>

        <div class="flex flex-col gap-y-2">
          <p class="block text-gray-700 text-sm font-bold mb-2">
            Do We Add VAT?
          </p>

          <div
            class="flex items-center ps-4 border bg-gray-200 border-gray-200 rounded dark:border-gray-700"
          >
            <input
              checked
              id="bordered-radio-2"
              type="radio"
              value="1.075"
              name="value_added_tax"
              class="w-4 h-4 form-input text-green-600 bg-white border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
            />
            <label
              for="bordered-radio-2"
              class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"
              >Yes</label
            >
          </div>

          <div
          class="flex items-center ps-4 border border-gray-200 rounded dark:border-gray-700 bg-gray-200"
        >
          <input
            id="bordered-radio-1"
            type="radio"
            value="1"
            name="value_added_tax"
            class="w-4 h-4 text-green-600 bg-white border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
          />
          <label
            for="bordered-radio-1"
            class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"
            >No</label
          >
        </div>
          <div></div>

          
        </div>


   
      </div>
    </div>

    <div class="inline-flex">
      <button
        class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center init_next"
      >
        Next
      </button>
    </div>
  </div>
</div>

templates/others/invoice_detail.html
<div class="invoice_detail hidden flex bg-green-200 flex-col gap-y-4 p-24">

  <h1 class="text-3xl font-bold text-red-600">Invoice Details</h1>
  <div class="flex flex-col gap-y-4">

    <div class="flex flex-row gap-x-4">

    <div class="flex flex-col gap-y-2">
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="invoice_id">
          Invoice ID
        </label>
        <input name="invoice_id" id="invoice_id" class="form-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 
      leading-tight focus:outline-none focus:shadow-outline" type="text" />
      <span class="invoice_id_error mt-4 text-red-500 italic"></span>
      </div>
    </div>

    <div class="flex flex-col gap-y-2">
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="company_name">
          Company Name
        </label>
        <input name="company_name" id="company_name"
          class="form-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          type="text" />
        <span class="company_name_error mt-4 text-red-500 italic"></span>
      </div>
    </div>
  </div>


    <div class="flex flex-col gap-y-2">
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="company_location">
          Company Location
        </label>
        <input name="company_location" id="company_location"
          class="form-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          type="text" />
        <span class="company_location_error mt-4 text-red-500 italic"></span>
      </div>
    </div>

    <div class="flex flex-col gap-y-2">
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="invoice_title">
          Invoice Title
        </label>

        <input name="invoice_title" id="invoice_title" class="form-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 
      leading-tight focus:outline-none focus:shadow-outline" type="text" />
      <span class="invoice_title_error mt-4 text-red-500 italic"></span>
    </div>
    </div>

    <div class="flex flex-col gap-y-2">
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="invoice_title">
          Invoice Date
        </label>
   

        <input name="invoice_date" id="invoice_date" class="form-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 
      leading-tight focus:outline-none focus:shadow-outline" type="date" />
      <span class="invoice_date_error mt-4 text-red-500 italic"></span>  
    </div>
    </div>

    <div class="flex flex-col gap-y-2">
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="invoice_title">
          Select Invoice Type
        </label>
    <select id="invoice_type"
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 
      dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
      <option value="US">Proforma Invoice</option>
      <option value="CA">Invoice</option>
      <option value="FR">Quote</option>
    </select>
    </div>
    </div>



    <div class="inline-flex">
      <button class="invoice_detail_prev bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-l">
        Previous
      </button>
      <button type="button"
        class="invoice_detail_next bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r">
        Next
      </button>
    </div>



  </div>
</div>

templates/others/navbar.html
{% load static %}
    <nav class="border-gray-200 bg-green-400">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <img src="{% static 'img/logo.png' %}" class="h-14" alt="Orange VFX Logo" />
        </a>
        {% if request.user.is_authenticated %}
        <div class="flex items-center md:order-2 space-x-1 md:space-x-0 rtl:space-x-reverse">
          <button type="button" data-dropdown-toggle="language-dropdown-menu"
            class="inline-flex items-center font-medium justify-center px-4 py-2 text-sm text-gray-900 dark:text-white rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white">
            <img src="{% static 'img/ovie_wale.png' %}" alt="" class="capitalize
            w-12 rounded-full mr-2"><span class="capitalize">{{ request.user }}</span>
          </button>
          <!-- Dropdown -->
          <div
            class="z-50 hidden my-4 text-base list-none divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700"
            id="language-dropdown-menu">
            <ul class="py-2 font-medium" role="none">
              <li>
                <a href="#"
                  class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                  role="menuitem">
                  <div class="inline-flex items-center px-4">
                    <img src="{% static 'img/logout.png' %}" alt="" class="w-6">
                    <a href="{% url 'accounts:logout' %}">Logout</a>
                  </div>
                </a>
              </li>
          
            </ul>
          </div>
          <button data-collapse-toggle="navbar-language" type="button"
            class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            aria-controls="navbar-language" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M1 1h15M1 7h15M1 13h15" />
            </svg>
          </button>
        </div>
        {% endif %}
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-language">
          {% if request.user.is_authenticated %}
          <ul
            class="flex flex-col font-medium p-4 md:p-0 mt-4  md:space-x-8 md:flex-row md:mt-0 
            md:border-0">
            <li>
              <a href="/"
                class="block py-2 px-3 text-white
                rounded md:text-blue-700 md:p-0 md:dark:text-blue-500"
                aria-current="page">Home</a>
            </li>
            <li>
              <a href="/salaries"
                class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 
                md:hover:bg-transparent md:hover:text-blue-700 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 
                dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Edit Salaries</a>
            </li>
            <li>
              <a href="cost/edit/1"
                class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 
                md:hover:bg-transparent md:hover:text-blue-700 dark:text-white md:dark:hover:text-blue-500 
                dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Edit Overhead Cost</a>
            </li>
          </ul>
          {% else %}
          <ul
            class="flex flex-col font-medium p-4 md:p-0 mt-4  md:space-x-8 md:flex-row md:mt-0 
            md:border-0">
            <li>
              <a href="{% url 'accounts:login' %}"
                class="block py-2 px-3 text-white
                rounded md:text-orange-700 md:p-0 md:dark:text-orange-500"
                aria-current="page">Sign In</a>
            </li>
            <li>
              <a href="{% url 'accounts:register' %}"
                class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 
                md:hover:bg-transparent md:hover:text-orange-700 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 
                dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Register</a>
            </li>
       
          </ul>
          {% endif %}


        </div>
      </div>
    </nav>